import api from './api';

/**
 * Authentication service for handling auth-related API calls
 */
const AuthService = {
  /**
   * Login a user
   * @param {string} email - User email
   * @param {string} password - User password
   * @returns {Promise<Object>} User data with token
   */
  login: async (email, password) => {
    try {
      // Backend expects either username or email
      const response = await api.post('/auth/login', { 
        email, 
        password,
        // Include username as null to match backend expectations
        username: null 
      });

      // Store the token in localStorage
      if (response.token) {
        localStorage.setItem('token', response.token);
      }

      return response;
    } catch (error) {
      console.error('Login error:', error);
      throw error;
    }
  },

  /**
   * Register a new user
   * @param {string} username - User username
   * @param {string} name - User name
   * @param {string} email - User email
   * @param {string} password - User password
   * @returns {Promise<Object>} User data with token
   */
  register: async (username, name, email, password) => {
    try {
      // Split name into firstName and lastName
      const nameParts = name.split(' ');
      const firstName = nameParts[0];
      const lastName = nameParts.length > 1 ? nameParts.slice(1).join(' ') : '';

      const response = await api.post('/auth/register', { 
        username, 
        email, 
        password,
        firstName,
        lastName
      });

      // Store the token in localStorage
      if (response.token) {
        localStorage.setItem('token', response.token);
      }

      return response;
    } catch (error) {
      console.error('Registration error:', error);
      throw error;
    }
  },

  /**
   * Logout the current user
   * @returns {Promise<void>}
   */
  logout: async () => {
    try {
      // The backend doesn't have a logout endpoint
      // Just remove the token from localStorage
      localStorage.removeItem('token');
    } catch (error) {
      console.error('Logout error:', error);
      throw error;
    }
  },

  /**
   * Get the current user's profile
   * @returns {Promise<Object>} User profile data
   */
  getCurrentUser: async () => {
    try {
      // Check if token exists
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('No authentication token found');
      }

      // Since the /auth/me endpoint doesn't exist in the backend,
      // we'll use the token information directly
      // In a real application, this should be replaced with a proper API call
      // when the backend endpoint is implemented

      // Parse the base64 token as generated by the backend
      // The backend generates a token with format "id:username:roles"
      try {
        const decodedData = atob(token);
        const [id, username, roles] = decodedData.split(':');

        // Create a user object from the token data
        return {
          id: parseInt(id),
          username: username,
          roles: roles ? roles.split(',') : [],
          // Add other default user properties
          email: '',
          firstName: '',
          lastName: ''
        };
      } catch (e) {
        console.error('Error decoding token:', e);
        throw new Error('Invalid token format');
      }
    } catch (error) {
      console.error('Get current user error:', error);
      throw error;
    }
  },

  /**
   * Check if the user is authenticated
   * @returns {boolean} True if the user is authenticated
   */
  isAuthenticated: () => {
    return !!localStorage.getItem('token');
  }
};

export default AuthService;
